Fix versioning with a release-type.txt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -104,11 +104,78 @@ jobs:
           name: backend-artifacts
           path: ./artifacts
 
-  create-release:
-    name: Create Release
+  get-previous-release:
+    name: Get Previous Release
     needs:
       - build-frontend
       - build-backend
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Check out Code
+        uses: actions/checkout@v2
+
+      - name: Get Latest Release
+        id: get-release
+        run: |
+          # Use the GitHub API to fetch the latest release
+          GITHUB_TOKEN=$GITHUB_TOKEN
+          repo_owner=$GITHUB_REPOSITORY_OWNER
+          repo_name=$GITHUB_REPOSITORY_NAME
+          latest_release=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
+            -H "Accept: application/vnd.github.v3+json" \
+            "https://api.github.com/repos/$repo_owner/$repo_name/releases/latest" | jq -r .tag_name)
+          echo "::set-output name=previous-release::$latest_release"
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
+
+  read-release-type:
+    name: Check Release Type in telease-type.txt
+    runs-on: ubuntu-latest
+    needs: get-previous-release
+
+    steps:
+      - name: Read Release Type
+        id: read-release-type
+        run: |
+          # Read the release-type.txt file in the root directory
+          release_type=$(cat release-type.txt)
+          echo "::set-output name=release-type::$release_type"
+        shell: bash
+
+  calculate-version:
+    name: Calculate Version
+    needs: [get-previous-release, read-release-type]
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Calculate New Version
+        id: calculate-version
+        run: |
+          previous_release=${{ needs.get-previous-release.outputs.previous-release }}
+          release_type=${{ needs.read-release-type.outputs.release-type }}
+          
+          case "$release_type" in
+            major)
+              new_version=$(semver -i major "$previous_release")
+              ;;
+            minor)
+              new_version=$(semver -i minor "$previous_release")
+              ;;
+            patch)
+              new_version=$(semver -i patch "$previous_release")
+              ;;
+            *)
+              echo "Invalid release type: $release_type" >&2
+              exit 1
+              ;;
+          esac
+          echo "::set-output name=new-version::$new_version"
+        shell: bash
+
+  create-release:
+    name: Create Release
+    needs: calculate-version
     runs-on: ubuntu-latest
 
     steps:
@@ -122,7 +189,7 @@ jobs:
           path: ./artifacts/frontend
 
       - name: Download Artifacts (Backend)
-        uses: actions/download-artifact@v2
+        uses: actions/download-artifact@v3
         with:
           name: backend-artifacts
           path: ./artifacts/backend
@@ -131,6 +198,7 @@ jobs:
         uses: softprops/action-gh-release@v1
         with:
           files: ./artifacts/frontend/* ./artifacts/backend/*
+          tag_name: ${{ needs.calculate-version.outputs.new_version }}
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
 
